@startuml
left to right direction
skinparam actorStyle awesome

actor "Secretaría" as Secretaria

rectangle "Gestión de Dispensas Académicas" {
  usecase "Registrar solicitud de dispensa académica" as CU11
  usecase "Adjuntar documentación a dispensa" as CU12
  usecase "Ver estado de dispensa" as CU13
  usecase "Actualizar dispensa académica" as CU14
  usecase "Generar informe de dispensas" as CU15
}

Secretaria --> CU11
Secretaria --> CU12
Secretaria --> CU13
Secretaria --> CU14
Secretaria --> CU15

@enduml
