@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #F0F0F0
  BorderColor #333
  ArrowColor #333
}

actor Secretaria

rectangle "GestiónListasAlumnos()" {
  usecase "abrirLista()" as CU01
  usecase "importarMatricula()" as CU02
  usecase "verDetalleMatricula()" as CU03
  usecase "cerrarMatricula()" as CU04
  usecase "exportarListado()" as CU05
}


rectangle "Gestión de Dispensas Académicas" {
  usecase "CrearSolicitudDispensa()" as CU11
  usecase "consultarSolicitudDispensa()" as CU12
  usecase "editarSolicitudDispensa()" as CU13
  usecase "exportarDispensa()" as CU14
  usecase "guardarSolicitud()" as CU15
  usecase "cerrarSolicitud()" as CU16
   
   
}

Secretaria --> CU01
Secretaria --> CU02
Secretaria --> CU03
Secretaria --> CU04
Secretaria --> CU05

Secretaria --> CU11
Secretaria --> CU12
Secretaria --> CU13
Secretaria --> CU14
Secretaria --> CU15
Secretaria --> CU16

@enduml