@startuml CrearSolicitudDispensa
title Crear solicitud de dispensa
skinparam linetype polyline

state DISPENSAS_ABIERTO_INICIAL  as "DISPENSAS_ABIERTO"
state SOLICITUD_DISPENSA_ABIERTA_FINAL as "SOLICITUD_DISPENSA_ABIERTA"

DISPENSAS_ABIERTO_INICIAL -[#green]-> crearSolicitudDispensa

state crearSolicitudDispensa as "crearSolicitudDispensa()" {

    state " " as FormularioDatos
    state " " as DecidirAccion

    [*] -[#green]-> FormularioDatos
    note on link
    <b>Alumno</b> se encuentra en DISPENSAS_ABIERTO
    (listado de sus solicitudes) y selecciona
    "Nueva solicitud de dispensa".
    end note

    FormularioDatos -[#green]-> DecidirAccion
    note on link
    <b>Sistema</b> presenta un formulario en blanco.

    <b>Alumno</b> introduce los datos requeridos:
    • Asignatura / periodo
    • Motivo de la dispensa
    • (Opcional) documentación adjunta

    Al finalizar, el Alumno puede:
    • guardarSolicitud(), o
    • cerrarSolicitud() sin guardar cambios.
    end note

    DecidirAccion -[#green]-> [*]
    note on link
    <b>Sistema</b> ejecuta la acción elegida
    (guardarSolicitud() o cerrarSolicitud()).
    end note
}

' Si el alumno guarda, se crea y queda abierta
crearSolicitudDispensa -[#green]-> SOLICITUD_DISPENSA_ABIERTA_FINAL : guardarSolicitud() / cerrarSolicitud()

@enduml