@startuml Sistema de gestión
title Sistema de gestión de alumnos, matrículas y dispensas

class Alumno {
}

class Asignatura {
}

class Matricula {
  porcentajeAsistencia
  numeroFaltas
}

class SesionAsignatura {
}

class Dispensa {
  estadoDispensa
}

class Profesor {
}

class Director {
}

class Secretaria {
}

class OrdenacionAcademica {
}

Profesor <|-- Director
Alumno "1" --> "0..*" Matricula : realizaMatricula >
Asignatura "1" --> "0..*" Matricula : defineMatricula >
Asignatura "1" --> "0..*" SesionAsignatura : programaSesion >
Profesor "1" --> "0..*" SesionAsignatura : imparteSesion >
Matricula "0..*" --> "0..*" SesionAsignatura : participaEnSesion >
Alumno "1" --> "0..*" Dispensa : solicitaDispensa >
Dispensa "1" --> "1" Asignatura : referenciaAsignatura >
Director "1" --> "0..*" Dispensa : revisaDispensa >
Secretaria "1" --> "0..*" Dispensa : gestionaDispensa >
Profesor "1" --> "0..*" Asignatura : coordinaAsignatura >

OrdenacionAcademica ..> Asignatura : administraListas >
OrdenacionAcademica ..> Matricula : gestionaMatriculas >

@enduml
