@startuml
title Cerrar Sesion Clase

skinparam linetype polyline

state SESION_ASISTENCIA_ABIERTA_INICIAL as "SESION_ASISTENCIA_ABIERTA"
state ASISTENCIAS_ABIERTO_FINAL as "ASISTENCIAS_ABIERTO"

SESION_ASISTENCIA_ABIERTA_INICIAL -[#green]-> cerrarSesionClase

state cerrarSesionClase as "cerrarSesionClase()" {

    state " " as ConfirmacionSalida
    state " " as LimpiandoVista

    [*] -[#green]-> ConfirmacionSalida
    note on link
    <b>Profesor</b> solicita salir de la toma de asistencia
    end note

    ConfirmacionSalida -[#green]-> LimpiandoVista
    note on link
    <b>Sistema</b> verifica que no haya cambios sin guardar
    end note

    LimpiandoVista -[#green]-> [*]
    note on link
    <b>Sistema</b> redirige al panel principal de asistencias
    end note

}

cerrarSesionClase -[#green]-> ASISTENCIAS_ABIERTO_FINAL

@enduml
