@startuml cerrarSesionClase
title Cerrar Sesión Clase
skinparam nodesep 100
skinparam ranksep 100
skinparam linetype ortho
skinparam Padding 10

state SESION_ASISTENCIA_ABIERTA_INICIAL as "SESION_ASISTENCIA_ABIERTA"
state ASISTENCIAS_ABIERTO_FINAL         as "ASISTENCIAS_ABIERTO"

[*] -[#green]-> SESION_ASISTENCIA_ABIERTA_INICIAL

SESION_ASISTENCIA_ABIERTA_INICIAL -[#green]-> ASISTENCIAS_ABIERTO_FINAL : cerrarSesionClase()
note left on link
    <b>Profesor solicita</b> cerrar la sesión actual.
    <b>Sistema registra</b> la hora de finalización.
    <b>Sistema muestra</b> el listado de asistencias.
end note

ASISTENCIAS_ABIERTO_FINAL -[#blue]-> [*]

@enduml