@startuml
title Consultar Lista Alumnos

skinparam linetype polyline

state LISTAS_ABIERTO_INICIAL as "LISTAS_ABIERTO"
state LISTAS_ABIERTO_FINAL as "LISTAS_ABIERTO"

LISTAS_ABIERTO_INICIAL -[#green]-> consultarListaAlumnos

state consultarListaAlumnos as "consultarListaAlumnos()" {

    state " " as SolicitandoCriterios
    state " " as ListaRenderizada

    [*] -[#green]-> SolicitandoCriterios
    note on link
    <b>Profesor</b> solicita ver lista de alumnos
    end note

    SolicitandoCriterios -[#green]-> ListaRenderizada
    note on link
    <b>Sistema</b> solicita selección de curso/grado
    
    <b>Profesor</b> selecciona el curso asignado

    <b>Sistema</b> recupera listado de alumnos matriculados
    end note

    ListaRenderizada -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta la lista de alumnos
    end note

}

consultarListaAlumnos -[#green]-> LISTAS_ABIERTO_FINAL

@enduml