@startuml
title Consultar Historial Asistencias

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "ASISTENCIAS_ABIERTO"
state endState as "ASISTENCIAS_ABIERTO"

startState --> consultarHistorialAsistencias
note on link
    <b>Usuario selecciona</b>
    Consultar Historial de asistencias
end note

state consultarHistorialAsistencias {
    state SeleccionFiltros as " "
    state ValidarBusqueda <<choice>>

    [*] --> SeleccionFiltros
    note on link
        <b>Sistema solicita criterios</b>
        * Rango de fechas
        * Grupo o Alumno
    end note

    SeleccionFiltros --> ValidarBusqueda
    note on link
        <b>Usuario introduce</b>
        Filtros de búsqueda
    end note

    ValidarBusqueda -[#red]-> SeleccionFiltros
    note on link
        <b>Sistema informa</b>
        Error
    end note

    ValidarBusqueda --> [*]
    note on link
        <b>Sistema muestra</b>
        Historial de asistencias
    end note
}

consultarHistorialAsistencias --> endState

@enduml