@startuml
title Consultar Lista Alumnos

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "LISTAS_ABIERTO"
state endState as "LISTAS_ABIERTO"

startState --> consultarListaAlumnos
note on link
    <b>Usuario selecciona</b>
    Consultar Lista
end note

state consultarListaAlumnos {
    state SeleccionGrupo as " "
    state ValidarExistencia <<choice>>

    [*] --> SeleccionGrupo
    note on link
        <b>Sistema solicita</b>
        Selección de Curso/Grupo
    end note

    SeleccionGrupo --> ValidarExistencia
    note on link
        <b>Usuario selecciona</b>
        * Grado / Año
    end note

    ValidarExistencia -[#red]-> SeleccionGrupo
    note on link
        <b>Sistema informa</b>
        Error
    end note

    ValidarExistencia --> [*]
    note on link
        <b>Sistema muestra</b>
        Listado de alumnos matriculados
    end note
}

consultarListaAlumnos --> endState

@enduml