@startuml
title Consultar Dispensas Alumno

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "DISPENSAS_ABIERTO"
state endState as "DISPENSAS_ABIERTO"

startState --> consultarDispensasAlumno
note on link
    <b>Usuario selecciona</b>
    Consultar dispensas de alumno
end note

state consultarDispensasAlumno {
    state IngresoDatos as " "
    state ValidarAlumno <<choice>>

    [*] --> IngresoDatos
    note on link
        <b>Sistema solicita</b>
        Identificación del alumno
    end note

    IngresoDatos --> ValidarAlumno
    note on link
        <b>Usuario introduce</b>
        * Nombre/DNI/Identificador
    end note

    ValidarAlumno -[#red]-> IngresoDatos
    note on link
        <b>Sistema informa</b>
        Error
    end note

    ValidarAlumno --> [*]
    note on link
        <b>Sistema muestra</b>
        Listado de dispensas del alumno
    end note
}

consultarDispensasAlumno --> endState

@enduml