@startuml
title Consultar Dispensas Alumno

skinparam linetype polyline

state DISPENSAS_ABIERTO_INICIAL as "DISPENSAS_ABIERTO"
state DISPENSAS_ABIERTO_FINAL as "DISPENSAS_ABIERTO"

DISPENSAS_ABIERTO_INICIAL -[#green]-> consultarDispensasAlumno

state consultarDispensasAlumno as "consultarDispensasAlumno()" {

    state " " as SolicitandoBusqueda
    state " " as ResultadosDispensas

    [*] -[#green]-> SolicitandoBusqueda
    note on link
    <b>Profesor</b> solicita consultar
    las dispensas de un alumno
    end note

    SolicitandoBusqueda -[#green]-> ResultadosDispensas
    note on link
    <b>Sistema</b> solicita identificar al alumno
    
    <b>Profesor</b> selecciona al alumno

    <b>Sistema</b> recupera dispensas asociadas al alumno
    end note

    ResultadosDispensas -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta las dispensas encontradas
    end note

}

consultarDispensasAlumno -[#green]-> DISPENSAS_ABIERTO_FINAL

@enduml