@startuml
title Consultar Historial Asistencias

skinparam linetype polyline

state ASISTENCIAS_ABIERTO_INICIAL as "ASISTENCIAS_ABIERTO"
state ASISTENCIAS_ABIERTO_FINAL as "ASISTENCIAS_ABIERTO"

ASISTENCIAS_ABIERTO_INICIAL -[#green]-> consultarHistorialAsistencias

state consultarHistorialAsistencias as "consultarHistorialAsistencias()" {

    state " " as SeleccionFiltros
    state " " as VisualizandoHistorial

    [*] -[#green]-> SeleccionFiltros
    note on link
    <b>Profesor</b> solicita ver historial
    de asistencias
    end note

    SeleccionFiltros -[#green]-> VisualizandoHistorial
    note on link
    <b>Sistema</b> compila estadísticas:
    • % de asistencia
    • Listado de ausencias por fecha
    end note

    VisualizandoHistorial -[#green]-> [*]
    note on link
    <b>Sistema</b> muestra el reporte de asistencias
    end note

}

consultarHistorialAsistencias -[#green]-> ASISTENCIAS_ABIERTO_FINAL

@enduml