@startuml
title Crear Sesion Clase

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "ASISTENCIAS_ABIERTO"
state endState as "SESION_ASISTENCIA_ABIERTA"

startState --> crearSesionClase
note on link
    <b>Usuario selecciona</b>
    Nueva Sesión
end note

state crearSesionClase {
    state FormularioSesion as " "
    state ValidarDatosSesion <<choice>>

    [*] --> FormularioSesion
    note on link
        <b>Sistema solicita</b>
        Datos de la clase
    end note

    FormularioSesion --> ValidarDatosSesion
    note on link
        <b>Usuario introduce</b>
        * Fecha y Hora
        * Curso / Asignatura
        * Tema (opcional)
    end note

    ValidarDatosSesion -[#red]-> FormularioSesion
    note on link
        <b>Sistema informa</b>
        Error
    end note

    ValidarDatosSesion --> [*]
    note on link
        <b>Sistema crea</b>
        * Sesión
        * Lista de alumnos
    end note
}

crearSesionClase --> endState

@enduml