@startuml
title Registrar Toma Asistencia

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "SESION_ASISTENCIA_ABIERTA"
state endState as "ASISTENCIAS_ABIERTO"

startState --> registrarTomaAsistencia
note on link
    <b>Usuario selecciona</b>
    registrarTomaAsistencia
end note

state registrarTomaAsistencia {
    state MarcadoDeAlumnos as " "
    state ValidarCompletitud <<choice>>

    [*] --> MarcadoDeAlumnos
    note on link
        <b>Usuario asigna estados</b>
        Para cada alumno de la lista
    end note

    MarcadoDeAlumnos --> ValidarCompletitud
    note on link
        <b>Usuario confirma</b>
        Guardar Asistencia
    end note

    ValidarCompletitud -[#red]-> MarcadoDeAlumnos
    note on link
        <b>Sistema informa</b>
        Error
    end note

    ValidarCompletitud --> [*]
    note on link
        <b>Sistema procesa</b>
        Guarda los registros y 
        cierra la sesión de clase
    end note
}

registrarTomaAsistencia --> endState

@enduml