@startuml
title Registrar Toma Asistencia

skinparam linetype polyline

state SESION_ASISTENCIA_ABIERTA_INICIAL as "SESION_ASISTENCIA_ABIERTA"
state SESION_ASISTENCIA_ABIERTA_FINAL as "SESION_ASISTENCIA_ABIERTA"

SESION_ASISTENCIA_ABIERTA_INICIAL -[#green]-> registrarTomaAsistencia

state registrarTomaAsistencia as "registrarTomaAsistencia()" {

    state " " as VerificandoEstado
    state " " as GuardadoConfirmado

    [*] -[#green]-> VerificandoEstado
    note on link
    <b>Profesor</b> ha marcado las asistencias
    y solicita finalizar la toma de asistencias
    end note

    VerificandoEstado -[#green]-> GuardadoConfirmado
    note on link
    <b>Sistema</b> valida los datos ingresados
    
    <b>Sistema</b> registra la asistencia:
    • Guarda estados (Presente, Ausente, Tarde)
    • Asocia la sesión al historial del curso
    end note

    GuardadoConfirmado -[#green]-> [*]
    note on link
    <b>Sistema</b> confirma el guardado exitoso
    end note

}

registrarTomaAsistencia -[#green]-> SESION_ASISTENCIA_ABIERTA_FINAL

@enduml
