@startuml
title Registrar Toma Asistencia

skinparam linetype polyline

state SESION_ASISTENCIA_ABIERTA_INICIAL as "SESION_ASISTENCIA_ABIERTA"
state ASISTENCIAS_ABIERTO_FINAL as "ASISTENCIAS_ABIERTO"

SESION_ASISTENCIA_ABIERTA_INICIAL -[#green]-> registrarTomaAsistencia

state registrarTomaAsistencia as "registrarTomaAsistencia()" {

    state " " as VerificandoEstado
    state " " as GuardadoConfirmado

    [*] -[#green]-> VerificandoEstado
    note on link
    <b>Profesor</b> ha marcado las asistencias
    y solicita finalizar la toma de asistencias
    end note

    VerificandoEstado -[#green]-> GuardadoConfirmado
    note on link
    <b>Sistema</b> valida los datos ingresados
    
    <b>Sistema</b> registra la asistencia:
    • Guarda estados (Presente, Ausente, Tarde)
    • Asocia la sesión al historial del curso
    end note

    GuardadoConfirmado -[#green]-> [*]
    note on link
    <b>Sistema</b> confirma el guardado exitoso

    <b>Sistema</b> cierra la sesión de clase
    y vuelve al panel general de asistencias
    end note

}

registrarTomaAsistencia -[#green]-> ASISTENCIAS_ABIERTO_FINAL

@enduml