@startuml
title Ver Detalle Alumno

skinparam linetype polyline

state ALUMNOS_ABIERTO_INICIAL as "ALUMNOS_ABIERTO"
state ALUMNO_ABIERTO_FINAL as "ALUMNO_ABIERTO"

ALUMNOS_ABIERTO_INICIAL -[#green]-> verDetalleAlumno

state verDetalleAlumno as "verDetalleAlumno()" {

    state " " as SeleccionEnLista
    state " " as DetalleCargado

    [*] -[#green]-> SeleccionEnLista
    note on link
    <b>Profesor</b> busca un alumno específico
    en el listado general
    end note

    SeleccionEnLista -[#green]-> DetalleCargado
    note on link
    <b>Profesor</b> selecciona al alumno

    <b>Sistema</b> recupera ficha completa:
    • Datos personales
    • Informacion sobre dispensas y asistencias
    • Otros datos
    end note

    DetalleCargado -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta la ficha del alumno

    <b>Sistema</b> cambia contexto a ALUMNO_ABIERTO
    end note

}

verDetalleAlumno -[#green]-> ALUMNO_ABIERTO_FINAL

@enduml
