@startuml
title Ver Detalle Alumno

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "ALUMNOS_ABIERTO"
state endState as "ALUMNO_ABIERTO"

startState --> verDetalleAlumno
note on link
    <b>Usuario selecciona</b>
    Alumno de la lista
end note

state verDetalleAlumno {
    state RecuperandoDatos as " "
    state ValidarSeleccion <<choice>>

    [*] --> RecuperandoDatos
    note on link
        <b>Sistema identifica</b>
        Alumno seleccionado
    end note

    RecuperandoDatos --> ValidarSeleccion
    note on link
        <b>Sistema</b>
        Carga ficha completa
    end note

    ValidarSeleccion -[#red]-> [*]
    note on link
        <b>Sistema informa</b>
        Error al cargar datos
    end note

    ValidarSeleccion --> [*]
    note on link
        <b>Sistema muestra</b>
        Ficha detallada del alumno
    end note
}

verDetalleAlumno --> endState
@enduml