@startuml Matricula_Estado
title Estado de Matricula en el CGU

[*] --> No_disponible

No_disponible --> Disponible : importarMatriculas()
Disponible     --> No_disponible : dejarDeImportarMatricula()

Disponible     --> [*]
No_disponible  --> [*]

@enduml
