@startuml
left to right direction
skinparam packageStyle rectangle

actor Alumno

rectangle "Sistema de Gestión Universitaria (CGU)" {

    package "Dispensas" {
        usecase "solicitarDispensa()" as SolicitarDispensa
        usecase "editarSolicitudDispensa()" as EditarSolicitudDispensa
        usecase "borrarSolicitudDispensa()" as BorrarSolicitudDispensa
        usecase "verSolicitudDispensa()" as VerSolicitudDispensa
        usecase "apelarDispensa()" as ApelarDispensa
    }

}

Alumno --> SolicitarDispensa
Alumno --> EditarSolicitudDispensa
Alumno --> BorrarSolicitudDispensa
Alumno --> VerSolicitudDispensa
Alumno --> ApelarDispensa

@enduml