@startuml
top to bottom direction

together{
  class Secretaría{}
  class DirectorDeGrado{}
}

together{
  class Dispensa{}
  class ListaDeAlumnos{}
}

together{
  class Alumno{}
  class Asignatura{}
  class Profesor{}
}

together{
  class Sesión{}
}



DirectorDeGrado -d-|> Profesor
DirectorDeGrado --> Dispensa: revisa

Secretaría -d-> Dispensa : gestor de
Secretaría -> DirectorDeGrado : avisa

Profesor "1" -l-> "1..*" Asignatura : responsable de
Profesor -l-> Sesión : imparte

Alumno "1" -u-> "0..*" Dispensa : solicita
Alumno -r-> Asignatura : matriculado en

Asignatura -d-> Sesión : compuesta por
Asignatura -u-> ListaDeAlumnos : tiene

Dispensa "1" --> "1..*" Sesión : aplica a
' Dispensa --> ListaDeAlumnos : modifica

ListaDeAlumnos -u-> Alumno : contiene


@enduml