@startuml
title Estados de Profesor

[*] --> Disponible

Disponible --> ImpartiendoSesion : iniciarSesion
ImpartiendoSesion --> TomandoAsistencia : registrarAsistencia
TomandoAsistencia --> ImpartiendoSesion : guardarAsistencia
ImpartiendoSesion --> Disponible : finalizarClase

@enduml
