@startuml Asistencia
title Modelo Conceptual - Toma de Asistencia

class Profesor {
}

class Asignatura {
}

class Estudiante {
}

class SesionDeClase {
  +fecha
}

class RegistroAsistencia {
 +estado : 'Presente, Ausente, Justificado, Dispensa
}

' ===== RELACIONES =====
Profesor -- Asignatura : imparte >
Asignatura -- SesionDeClase : programa >
Asignatura -- Estudiante : contiene matriculado >
Profesor -- RegistroAsistencia : realiza >
SesionDeClase -- RegistroAsistencia : contiene >
Estudiante -- SesionDeClase : asiste >
@enduml
