@startuml Alumno_Dispensas
left to right direction
skinparam packageStyle rectangle

actor Alumno

rectangle "Sistema de Gestión Universitaria (CGU)" {

    package "Dispensas" {
        usecase "crearSolicitudDispensa()"  as CrearSolicitudDispensa
        usecase "verEstadoDispensa()"       as VerEstadoDispensa
        usecase "editarSolicitudDispensa()" as EditarSolicitudDispensa
        usecase "guardarSolicitud()"        as GuardarSolicitud
        usecase "cerrarSolicitud()"         as CerrarSolicitud
    }

}

Alumno --> CrearSolicitudDispensa
Alumno --> VerEstadoDispensa
Alumno --> EditarSolicitudDispensa
Alumno --> GuardarSolicitud
Alumno --> CerrarSolicitud
@enduml