@startuml VerEstadoDispensa

title Ver estado de dispensa
skinparam linetype polyline

state DISPENSAS_ABIERTO_INICIAL as "DISPENSAS_ABIERTO"
state SOLICITUD_DISPENSA_ABIERTA_FINAL as "SOLICITUD_DISPENSA_ABIERTA"

DISPENSAS_ABIERTO_INICIAL -[#green]-> verEstadoDispensa

state verEstadoDispensa as "verEstadoDispensa()" {

    state " " as SeleccionSolicitud
    state " " as EstadoMostrado

    [*] -[#green]-> SeleccionSolicitud
    note on link
    <b>Alumno</b> está en DISPENSAS_ABIERTO
    viendo el listado de <u>sus</u> solicitudes
    y decide consultar el estado de una de ellas.
    end note

    SeleccionSolicitud -[#green]-> EstadoMostrado
    note on link
    <b>Alumno</b> selecciona una solicitud concreta.

    <b>Sistema</b> recupera la información
    y su estado actual.
    end note

    EstadoMostrado -[#green]-> [*]
    note on link
    <b>Sistema</b> muestra el detalle de la solicitud
    y mantiene el contexto en SOLICITUD_DISPENSA_ABIERTA,
    desde donde el Alumno podrá:
    • cerrarSolicitud()
    end note
}

verEstadoDispensa -[#green]-> SOLICITUD_DISPENSA_ABIERTA_FINAL

@enduml
