@startuml CerrarCicloAcademico
title Cerrar ciclo académico

' --- CONFIGURACIÓN DE ESTILO ---
skinparam nodesep 100
skinparam ranksep 100
skinparam linetype ortho
skinparam Padding 10

' --- DEFINICIÓN DE ESTADOS CON ALIAS ---
state MATRICULAS_ABIERTO_INICIAL   as "MATRICULAS_ABIERTO"
state PROCESO_CIERRE_COMP          as "FINALIZANDO_CICLO"
state MATRICULAS_ABIERTO_FINAL     as "MATRICULAS_ABIERTO"

' Flujo inicial
[*] -[#green]-> MATRICULAS_ABIERTO_INICIAL

' Entrada al estado
MATRICULAS_ABIERTO_INICIAL -[#green]-> PROCESO_CIERRE_COMP : cerrarCicloAcademico()
note left on link
    <b>Secretaria solicita</b> cerrar el ciclo académico actual.
    <b>Sistema permite</b> acceder al módulo de cierre.
end note

' Estado Compuesto
state PROCESO_CIERRE_COMP {
    state ConfirmacionCierre as "Confirmación de Cierre"
   
    ' Inicio interno
    [*] -[#green]-> ConfirmacionCierre
   
    ' Nota sobre la actividad interna
    note right of ConfirmacionCierre
        <b>Sistema permite</b> retornar información resumida
        del ciclo para confirmación.
        <b>Secretaria solicita</b> ejecutar el cierre.
    end note
   
    ' Fin interno
    ConfirmacionCierre -[#green]-> [*]
}

' --- SALIDAS ---
PROCESO_CIERRE_COMP -[#green]---> MATRICULAS_ABIERTO_FINAL : confirmarCierre()
note right on link
    <b>CONFIRMAR:</b>
    <b>Sistema permite</b> procesar el cierre del ciclo
    y retornar al listado de matrículas del nuevo ciclo.
end note

PROCESO_CIERRE_COMP -[#red]---> MATRICULAS_ABIERTO_FINAL : cancelarCierre()
note left on link
    <b>CANCELAR:</b>
    <b>Secretaria solicita</b> cancelar la operación.
    <b>Sistema permite</b> regresar al listado principal.
end note

' Finalización del flujo
MATRICULAS_ABIERTO_FINAL -[#blue]-> [*]

@enduml
