@startuml
title Importar Matrículas


skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "MATRICULAS_ABIERTO"
state endState1 as "MATRICULA_ABIERTA"
state endState2 as "MATRICULAS_ABIERTO"

startState --> importarMatriculas
note on link
    <b>Usuario solicita</b>
    Importar Matrícula
end note

state importarMatriculas {
    state SolicitudArchivo as " "
    state ValidarFormato <<choice>>

    ' 1. Inicio: Solicita el archivo
    [*] --> SolicitudArchivo
    note on link
        <b>Sistema muestra interfaz</b>
        para adjuntar archivos a importar.
    end note

    ' 2. El usuario elige el archivo
    SolicitudArchivo --> ValidarFormato
    note on link
        <b>Usuario elige el archivo</b>
        con la matrícula.
    end note

    ' --- 3. FLUJO ALTERNATIVO (Error de formato - Camino Rojo) ---
    ValidarFormato -[#red]-> SolicitudArchivo
    note on link
        <b>Sistema verifica el formato</b>
        de los datos sea correcto.
        <b>Si hay error:</b>
        Sistema informa error y vuelve a solicitar.
    end note

    ' --- 4. FLUJO BÁSICO (Éxito) ---
    ValidarFormato --> ImportarRegistros
    
    state ImportarRegistros as " "
    note on link
        <b>Sistema importa los registros</b>
        de la matrícula.
    end note
    
    ImportarRegistros --> MostrarInforme
    
    state MostrarInforme as " "
    note on link
        <b>Sistema muestra un informe</b>
        del registro importado.
    end note
    
    MostrarInforme --> [*]
}


importarMatriculas --> endState1
note on link
    <b>verDetalleMatricula()</b>
    
end note

importarMatriculas --> endState2


@enduml