@startuml
title Cerrar Usuario

skinparam linetype polyline

state USUARIO_ABIERTO_INICIAL as "USUARIO_ABIERTO"
state USUARIOS_ABIERTO_FINAL as "USUARIOS_ABIERTO"

USUARIO_ABIERTO_INICIAL -[#green]-> cerrarUsuario

state cerrarUsuario as "cerrarUsuario()" {

    state " " as VerificacionEstado
    state " " as LimpiezaVista

    [*] -[#green]-> VerificacionEstado
    note on link
        <b>Administrador</b> decide volver al listado
        o cancelar la operación actual
    end note

    VerificacionEstado -[#green]-> LimpiezaVista
    note on link
        <b>Sistema</b> descarta cualquier cambio no guardado
    end note

    LimpiezaVista -[#green]-> [*]
    note on link
        <b>Sistema</b> redirige al panel de gestión de usuarios
    end note

}

cerrarUsuario -[#green]-> USUARIOS_ABIERTO_FINAL

@enduml
