@startuml
title Cerrar Detalle Matrícula

skinparam linetype polyline

state MATRICULA_ABIERTA_INICIAL as "MATRICULA_ABIERTA"
state MATRICULAS_ABIERTO_FINAL as "MATRICULAS_ABIERTO"

MATRICULA_ABIERTA_INICIAL -[#green]-> cerrarDetalleMatricula

state cerrarDetalleMatricula as "cerrarDetalleMatricula()" {

    state " " as SolicitudRetorno
    state " " as RetornoLista

    [*] -[#green]-> SolicitudRetorno
    note on link
    <b>Administrador</b> finaliza la revisión
    y solicita volver al listado
    end note

    SolicitudRetorno -[#green]-> RetornoLista
    note on link
    <b>Sistema</b> cierra la ficha actual
    end note

    RetornoLista -[#green]-> [*]
    note on link
      <b>Sistema</b> vuelve a la vista del listado
    de matrículas
    end note

}

cerrarDetalleMatricula -[#green]-> MATRICULAS_ABIERTO_FINAL

@enduml
