@startuml

title Desactivar Usuario

skinparam linetype polyline

state USUARIO_ABIERTO_INICIAL as "USUARIO_ABIERTO"
state USUARIO_ABIERTO_FINAL as "USUARIO_ABIERTO"

USUARIO_ABIERTO_INICIAL -[#green]-> desactivarUsuario

state desactivarUsuario as "desactivarUsuario()" {

    state " " as SolicitudConfirmacion
    state " " as EstadoActualizado

    [*] -[#green]-> SolicitudConfirmacion
    note on link
    <b>Administrador</b> solicita desactivar
    al usuario seleccionado
    end note

    SolicitudConfirmacion -[#green]-> EstadoActualizado
    note on link
    <b>Sistema</b> pide confirmación
    
    <b>Administrador</b> confirma la acción

    <b>Sistema</b> actualiza el estado del usuario:
    • Cambia estado a 'Inactivo'
    end note

    EstadoActualizado -[#green]-> [*]
    note on link
    <b>Sistema</b> confirma la desactivación

    <b>Sistema</b> permite solicitar:
    • modificarUsuario()
    • guardarUsuario()
    end note

}

desactivarUsuario -[#green]-> USUARIO_ABIERTO_FINAL

@enduml
