@startuml

title Editar Usuario

skinparam linetype polyline

state USUARIO_ABIERTO_INICIAL as "USUARIO_ABIERTO"
state USUARIO_ABIERTO_FINAL as "USUARIO_ABIERTO"

USUARIO_ABIERTO_INICIAL -[#green]-> editarUsuario

state editarUsuario as "editarUsuario()" {

    state " " as RecuperacionDatos
    state " " as EdicionEnCurso

    [*] -[#green]-> RecuperacionDatos
    note on link
      <b>Administrador</b> decide modificar los datos
    end note

    RecuperacionDatos -[#green]-> EdicionEnCurso
    note on link
      <b>Sistema</b> habilita los campos para su edición

    <b>Administrador</b> actualiza los campos necesarios
    end note

    EdicionEnCurso -[#green]-> [*]
    note on link
    <b>Sistema</b> valida los nuevos datos
    end note

}

editarUsuario -[#green]-> USUARIO_ABIERTO_FINAL

@enduml
