@startuml
title Guardar Usuario

skinparam linetype polyline

state USUARIO_ABIERTO_INICIAL as "USUARIO_ABIERTO"
state USUARIOS_ABIERTO_FINAL as "USUARIOS_ABIERTO"

USUARIO_ABIERTO_INICIAL -[#green]-> guardarUsuario

state guardarUsuario as "guardarUsuario()" {

    state " " as ValidacionFinal
    state " " as Persistencia

    [*] -[#green]-> ValidacionFinal
    note on link
        <b>Administrador</b> confirma la operación
    end note

    ValidacionFinal -[#green]-> Persistencia
    note on link
        <b>Sistema</b> registra los cambios
    end note

    Persistencia -[#green]-> [*]
    note on link
        <b>Sistema</b> notifica éxito de la operación
        y cierra la ficha del usuario
    end note

}

guardarUsuario -[#green]-> USUARIOS_ABIERTO_FINAL

@enduml
