@startuml
title Importar Matrículas

skinparam linetype polyline

state MATRICULAS_ABIERTO_INICIAL as "MATRICULAS_ABIERTO"
state MATRICULAS_ABIERTO_FINAL as "MATRICULAS_ABIERTO"

MATRICULAS_ABIERTO_INICIAL -[#green]-> importarMatriculas

state importarMatriculas as "importarMatriculas()" {

    state " " as SeleccionArchivo
    state " " as ValidacionEstructura
    state " " as CargaMasiva

    [*] -[#green]-> SeleccionArchivo
    note on link
    <b>Administrador</b> selecciona la opción de importar
    y carga el archivo con las matriculas
    end note

    SeleccionArchivo -[#green]-> ValidacionEstructura
    note on link
    <b>Sistema</b> analiza el archivo y verifica:
    • Que los datos indicados sean válidos
    end note

    ValidacionEstructura -[#green]-> CargaMasiva
    note on link
    <b>Sistema</b> registra las relaciones entre
    Alumnos y Cursos (Matriculación)
    end note

    CargaMasiva -[#green]-> [*]
    note on link
      <b>Sistema</b> confirma los nuevos registros
    y actualiza la vista de matrículas
    end note

}

importarMatriculas -[#green]-> MATRICULAS_ABIERTO_FINAL

@enduml
