@startuml

title Modificar Usuario

skinparam linetype polyline

state USUARIOS_ABIERTO_INICIAL as "USUARIOS_ABIERTO"
state USUARIO_ABIERTO_FINAL as "USUARIO_ABIERTO"

USUARIOS_ABIERTO_INICIAL -[#green]-> modificarUsuario

state modificarUsuario as "modificarUsuario()" {

    state " " as RecuperacionDatos
    state " " as EdicionEnCurso

    [*] -[#green]-> RecuperacionDatos
    note on link
    <b>Administrador</b> selecciona un usuario
    end note

    RecuperacionDatos -[#green]-> EdicionEnCurso
    note on link
    <b>Sistema</b> carga la información actual del usuario

    <b>Administrador</b> actualiza los campos necesarios
    end note

    EdicionEnCurso -[#green]-> [*]
    note on link
    <b>Sistema</b> valida los nuevos datos

    <b>Sistema</b> permite solicitar:
    • asignarRolUsuario()
    • desactivarUsuario()
    • guardarUsuario() (para confirmar cambios en BD)
    end note

}

modificarUsuario -[#green]-> USUARIO_ABIERTO_FINAL

@enduml
