@startuml
left to right direction
skinparam packageStyle rectangle

actor Alumno
actor Profesor
actor "Director De Grado" as DdD
actor "Secretaría Académica" as SA

package "Casos de Uso" {
    usecase "Solicitar Dispensa" as UC1
    usecase "Apelar Dispensa" as UC2
    usecase "Consultar Historial Académico" as UC3
    usecase "Asistir Sesión de Clase" as UC4

    usecase "Gestionar Sesión de Clase" as UC5
    usecase "Consultar Lista de Alumnos" as UC6
    usecase "Modificar Lista de Alumnos" as UC7
    usecase "Impartir Asignatura" as UC8

    usecase "Revisar Dispensa" as UC9
    usecase "Aprobar Dispensa" as UC10
    usecase "Rechazar Dispensa" as UC11
    usecase "Consultar Asignaturas / Cursos / Lista de Alumnos" as UC12

    usecase "Recibir Solicitud" as UC13
    usecase "Revisar Formato" as UC14
    usecase "Enviar Solicitud al Director" as UC15
    usecase "Recibir Decisión" as UC16
    usecase "Notificar Alumno" as UC17
    usecase "Gestionar Apelaciones" as UC18
}

' Conexiones alumno
Alumno --> UC1
Alumno --> UC2
Alumno --> UC3
Alumno --> UC4

' Relación extend: Apelar Dispensa depende de Solicitar Dispensa
UC1 <-[dashed]- UC2 : <<extend>>

' Conexiones profesor
Profesor --> UC5
Profesor --> UC6
Profesor --> UC7
Profesor --> UC8

' Conexiones director
DdD --> UC9
DdD --> UC10
DdD --> UC11
DdD --> UC12

' Conexiones Secretaría Académica
SA --> UC13
SA --> UC14
SA --> UC15
SA --> UC16
SA --> UC17
SA --> UC18


UC9 <-[dashed]- UC10 : <<includes>>
UC9 <-[dashed]- UC11 : <<includes>>

@enduml
