@startuml
left to right direction
skinparam packageStyle rectangle

actor DirectorDeGrado

rectangle "Sistema de Gestión Universitaria (CGU)" {

    package "Dispensas" {
        usecase "EditarSolicitud()" as DispensasEditarSolicitud
        usecase "ConsultarSolicitudDispensa()" as DispensasConsultarSolicitud

    }

    DirectorDeGrado --> DispensasConsultarSolicitud
    DirectorDeGrado --> DispensasEditarSolicitud
}

@enduml