@startuml
left to right direction
skinparam packageStyle rectangle

actor Profesor

rectangle "Sistema de Gestión Universitaria (CGU)" {

    package "Alumnos" {
        usecase "verDetalleAlumno()" as AlumnosVerDetalle
        usecase "importarAlumnos()" as AlumnosImportar
    }

    package "Asistencias" {
        usecase "crearSesionClase()" as AsistenciasCrearSesion
        usecase "cerrarSesionClase()" as AsistenciasCerrarSesion
        usecase "registrarTomaAsistencia()" as AsistenciasRegistrarToma
        usecase "exportarHistorialAsistencias()" as AsistenciasExportarHistorial
    }

    package "Dispensas" {
      usecase "consultarSolicitudDispensa()" as DispensasConsultar
    }

    Profesor --> AlumnosVerDetalle
    Profesor --> AlumnosImportar
    
    Profesor --> AsistenciasCrearSesion
    Profesor --> AsistenciasCerrarSesion
    Profesor --> AsistenciasRegistrarToma
    Profesor --> AsistenciasExportarHistorial
    
    Profesor --> DispensasConsultar
}

@enduml
