@startuml Administrador_CasosDeUso
title Casos de uso del Administrador
left to right direction
skinparam packageStyle rectangle

actor Administrador

rectangle "Gestión de usuarios y roles" {

    usecase "consultarUsuario()" as CU_Consultar
    usecase "crearUsuario()"     as CU_Crear
    usecase "editarUsuario()"    as CU_Editar
    usecase "guardarUsuario()"   as CU_Guardar
    usecase "cerrarUsuario()"    as CU_Cerrar
}

Administrador --> CU_Consultar
Administrador --> CU_Crear
Administrador --> CU_Editar
Administrador --> CU_Guardar
Administrador --> CU_Cerrar
@enduml