@startuml
title Consultar Lista Alumnos


skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "LISTAS_ABIERTO"
state endState as "LISTAS_ABIERTO"

startState --> consultarListaAlumno
note on link
    <b>Usuario solicita</b>
    Consultar Lista de Alumnos
end note

state consultarListaAlumno {
    state SolicitudFiltros as " "
    state ValidarConsulta <<choice>>

    [*] --> SolicitudFiltros
    note on link
        <b>Sistema solicita criterios</b>
        * Identificación: Profesor/Secretaria
    end note

    SolicitudFiltros --> ValidarConsulta
    note on link
        <b>Usuario introduce</b>
        * Asignatura
        * Año de curso
    end note

    ' --- FLUJO ALTERNATIVO (Error) ---
    ValidarConsulta -[#red]-> SolicitudFiltros
    note on link
        <b>Sistema valida:</b>
        * Existencia de Asignatura/Año
        <b>Si hay error:</b>
        Sistema informa error y vuelve a solicitar
    end note

    ' --- FLUJO BÁSICO (Éxito) ---
    ValidarConsulta --> [*]
    note on link
        <b>Sistema muestra</b>
        Listas de alumno consultadas
    end note
}

consultarListaAlumno --> endState

@enduml