@startuml Alumno_Estado
title Estado de Alumno en el CGU

[*] --> No_disponible

No_disponible --> Disponible : importarAlumnos()
Disponible --> No_disponible : dejarDeImportarAlumno()

Disponible --> [*]
No_disponible --> [*]

@enduml
