@startuml Alumno
title Diagrama de Estados: Alumno

[*] --> Preinscrito

Preinscrito --> Matriculado        : Alumno completa proceso de matrícula y es aceptado

Preinscrito --> DeBajaDefinitiva   : Alumno no formaliza matrícula

Matriculado --> EnBajaTemporal     : Alumno solicita una baja temporal

Matriculado --> DeBajaDefinitiva   : Alumno abandona definitivamente los estudios

Matriculado --> Graduado           : Alumno cumple todos los requisitos del grado

EnBajaTemporal --> Matriculado     : Alumno solicita reincorporación y la universidad la aprueba

EnBajaTemporal --> DeBajaDefinitiva: Alumno decide no reincorporarse o expira el plazo

Graduado --> [*]
DeBajaDefinitiva --> [*]

@enduml
