@startuml Asignatura
title Ciclo de vida de Asignatura

[*] --> Propuesta

Propuesta  --> Aprobada    : Órganos académicos aprueban la asignatura
Aprobada   --> Activa      : Universidad incorpora la asignatura a la oferta docente
Activa     --> EnExtincion : Se aprueba un nuevo plan o se decide extinguir la asignatura
EnExtincion --> Cerrada    : Finaliza la última edición y la asignatura deja de impartirse

Cerrada --> [*]

@enduml
