@startuml Toma de Asistencia
title Modelo Conceptual - Toma de Asistencia

class Profesor {
}

class Asignatura {
}

class Estudiante {
}

class SesionDeClase {
  +fecha
}

class TomaDeAsistencia {
}

' ===== RELACIONES =====
Profesor -- Asignatura : imparte >
Asignatura -- SesionDeClase : programa >
Asignatura -- Estudiante : contiene matriculado >
Profesor -- TomaDeAsistencia : registra >
SesionDeClase -- TomaDeAsistencia : se realiza >
Estudiante -- TomaDeAsistencia : asiste >
@enduml